apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sanders
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: docker-config
  params:
  - name: repo-url
    value: https://github.com/Sand-CloudShpaers/tekton-kadaster-project.git
  - name: image-reference
    value: container.registry.com/sublocation/my_app:version